### ISSUE TITLE
Как базу проинициализировать?

### ISSUE THREAD

**Issue by alxpanther** [Ivan-Skvortsov/yacut#1]
Здравствуйте.

Занялся докеризацией Вашего проекта. Все есть, все запускается, кроме того, что не работает. На страничке завожу ссылку и получаю в логах:

> sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: URL_map
> [SQL: SELECT "URL_map".id AS "URL_map_id", "URL_map".original AS "URL_map_original", "URL_map".short AS "URL_map_short", "URL_map".timestamp AS "URL_map_timestamp" 
> FROM "URL_map" 
> WHERE "URL_map".short = ?
> LIMIT ? OFFSET ?]
> [parameters: ('aaa', 1, 0)]
> (Background on this error at: https://sqlalche.me/e/14/e3q8)

Но это и логично, ведь базы sqlite нету. Я не силен в этом языке и понять как проинитить базу и с какими полями не могу.
Помогите, пожалуйста.

**Comment by Ivan-Skvortsov** [comment]
Здравствуйте!
Проект простенький, поэтому база здесь инициализировалась руками, через шелл фласка.
Для запуска в контейнере, как вариант, можно в [`__init__.py`](https://github.com/Ivan-Skvortsov/yacut/blob/master/yacut/__init__.py) последней строчкой добавить `db.create_all()`, тогда база и таблицы будут создаваться при запуске приложения (в том случае, если они не созданы).

**Comment by alxpanther** [comment]
Да, так сработало. Спасибо.
Мне нравится Ваше приложение. Коротко и без лишнего.
Мне тут для одного проекта как раз понадобилось что-то, что может сокращать ссылки и при этом, чтобы было простое в управлении. Я не программер, а девопс, по-этому написать такое сложновато, а вот заставить работать с пол пинка это по мне.
Привожу тут 2 файлика, чтобы упростить другим поднятие данного проекта. Останеться только повесить его на домен и прописать конфиг nginx.

Dockerfile:
```
FROM python:3.8-slim

MAINTAINER Alexander Fedorko <alx69@ukr.net>

LABEL maintainer="Alexander Fedorko <alx69@ukr.net>" \
 project_name="url-short" \
 from_os="OracleLinux 8"

ENV APP_ROOT /app/url-short
RUN mkdir -p /app/url-short

ADD ./yacut ${APP_ROOT}/

WORKDIR ${APP_ROOT}

RUN cd yacut && pip3 install --upgrade pip
RUN pip3 install -r requirements.txt

# ----- /entrypoint.sh -----
RUN echo '#!/bin/bash\n\
\n\
export FLASK_APP=yacut\n\
\n\
flask run --host=0.0.0.0' > /entrypoint.sh
RUN chmod ugo+rx /entrypoint.sh

EXPOSE 5000
ENTRYPOINT ["/entrypoint.sh"]

```

docker-compose.yml:
```
# git clone https://github.com/Ivan-Skvortsov/yacut.git
# touch db.sqlite3
# docker-compose up -d --build

version: "3.6"
services:

  short-url:
    build:
      context: .
    image: "short-url"
    container_name: "short-url"
    restart: always
    volumes:
      - "./db.sqlite3:/app/url-short/yacut/db.sqlite3"
    ports:
      - 5000:5000

```
и да, в конец 
> ... [__init__.py](https://github.com/Ivan-Skvortsov/yacut/blob/master/yacut/__init__.py) последней строчкой добавить db.create_all() ...

**Comment by Ivan-Skvortsov** [comment]
Рад помочь :smile:
